"""Service layer for the Dreaming system.

The Dreaming system consolidates short-term memory (ActionMemory entries)
into long-term knowledge (Second Brain notes). It runs three phases:

1. Light: Filter recent ActionMemory entries (last N days)
2. REM: Extract patterns, themes, and recurring issues
3. Deep: Promote high-value patterns to permanent notes in the Second Brain

Inspired by OpenClaw's memory-core dreaming system.
"""

import json
import logging
import math
from datetime import datetime, timedelta, timezone
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.dreaming.models import DreamingRun
from app.second_brain.models import Note
from app.second_brain import action_service
from app.second_brain.service import create_note as _create_note
from app.second_brain.action_models import ActionMemory

logger = logging.getLogger(__name__)


def _filter_recent_actions(
    actions: list[ActionMemory], days: int = 14
) -> list[ActionMemory]:
    """Light phase: filter ActionMemory entries from the last N days."""
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    result = []
    for a in actions:
        dt = a.created_at
        # Normalize naive datetimes (from SQLite) to offset-aware UTC
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        if dt >= cutoff:
            result.append(a)
    return result


def _extract_patterns(actions: list[ActionMemory]) -> dict[str, Any]:
    """REM phase: extract patterns from recent ActionMemory entries.

    Analyzes actions by:
    - Tag frequency (common tags = common themes)
    - Status distribution (success vs failure rates)
    - Action type clustering
    - Recurring error messages

    Returns a patterns dict with:
    - frequent_tags: [{tag, count}]
    - status_distribution: {status: count}
    - action_type_distribution: {type: count}
    - recurring_errors: [{message, count}]
    - top_categories: [{category, count}]
    """
    tag_counts: dict[str, int] = {}
    status_counts: dict[str, int] = {}
    type_counts: dict[str, int] = {}
    error_messages: dict[str, int] = {}
    category_counts: dict[str, int] = {}

    for action in actions:
        # Tag analysis
        tags = json.loads(action.tags) if action.tags else []
        for tag in tags:
            tag_counts[tag] = tag_counts.get(tag, 0) + 1

        # Status analysis
        status_counts[action.status] = status_counts.get(action.status, 0) + 1

        # Type analysis
        type_counts[action.action_type] = type_counts.get(action.action_type, 0) + 1

        # Error analysis (from metadata)
        if action.status == "failed":
            metadata = json.loads(action.metadata_json) if action.metadata_json else {}
            errors = metadata.get("errors", [])
            if isinstance(errors, list):
                for err in errors:
                    error_messages[str(err)] = error_messages.get(str(err), 0) + 1
            elif isinstance(errors, str):
                error_messages[errors] = error_messages.get(errors, 0) + 1

        # Category analysis (from tags)
        if action.tags:
            tag_list = json.loads(action.tags)
            for tag in tag_list:
                if tag.startswith("archon:"):
                    category = tag.split(":")[1] if ":" in tag else "unknown"
                    category_counts[category] = category_counts.get(category, 0) + 1

    # Filter to significant patterns (count >= 2)
    recurring_errors = [
        {"message": msg, "count": count}
        for msg, count in sorted(error_messages.items(), key=lambda x: -x[1])
        if count >= 2
    ][:10]

    frequent_tags = [
        {"tag": tag, "count": count}
        for tag, count in sorted(tag_counts.items(), key=lambda x: -x[1])
        if count >= 2
    ][:10]

    return {
        "frequent_tags": frequent_tags,
        "status_distribution": status_counts,
        "action_type_distribution": type_counts,
        "recurring_errors": recurring_errors,
        "top_categories": sorted(
            [{"category": cat, "count": count} for cat, count in category_counts.items()],
            key=lambda x: -x["count"],
        )[:5],
    }


async def _create_dream_note(
    db: AsyncSession,
    patterns: dict[str, Any],
    run: DreamingRun,
) -> Note | None:
    """Deep phase: create a Second Brain note from extracted patterns.

    The note summarizes:
    - What patterns were found
    - What recurring issues need attention
    - What capabilities are working well
    - Recommendations for self-improvement
    """
    lines = [
        f"# Dream Diary — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')}",
        "",
        f"Generated by BorgOS Dreaming system (run #{run.id}).",
        "",
        "## Summary",
        "",
        f"Analyzed {run.action_memories_analyzed} action memory entries.",
        f"Found {run.patterns_found} patterns.",
        "",
    ]

    # Status distribution
    dist = patterns.get("status_distribution", {})
    total = sum(dist.values()) if dist else 1
    success_rate = dist.get("success", 0) / total * 100 if total > 0 else 0
    lines.append(f"## Success Rate: {success_rate:.0f}%")
    lines.append("")
    for status, count in sorted(dist.items()):
        lines.append(f"- {status}: {count}")
    lines.append("")

    # Recurring errors
    errors = patterns.get("recurring_errors", [])
    if errors:
        lines.append("## Recurring Issues")
        lines.append("")
        for err in errors:
            lines.append(f"- **{err['count']}x**: {err['message']}")
        lines.append("")

    # Frequent tags
    tags = patterns.get("frequent_tags", [])
    if tags:
        lines.append("## Common Themes")
        lines.append("")
        for tag in tags:
            lines.append(f"- {tag['tag']} ({tag['count']}x)")
        lines.append("")

    # Recommendations
    lines.append("## Recommendations")
    lines.append("")
    if errors:
        lines.append("- Investigate and fix recurring failures")
    if success_rate < 50:
        lines.append("- Success rate is low — review workflow configurations")
    lines.append("- Consider creating new skills for frequent task patterns")
    lines.append("- Schedule next dreaming run for continued consolidation")
    lines.append("")

    content = "\n".join(lines)

    note = await _create_note(
        db,
        title=f"Dream Diary — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        content=content,
        tags=["dreaming", "self-improvement", "memory-consolidation"],
    )
    return note


async def run_dreaming_cycle(
    db: AsyncSession,
    days: int = 14,
    min_actions: int = 5,
) -> dict[str, Any]:
    """Run a complete Dreaming consolidation cycle.

    Args:
        db: Database session
        days: Number of days to look back for ActionMemory
        min_actions: Minimum actions required to run dreaming

    Returns:
        Summary dict with counts and note title
    """
    # Create run record
    run = DreamingRun(status="running")
    db.add(run)
    await db.flush()
    await db.refresh(run)

    # Push SSE event
    from app.task_automation.scheduler import sse_queue
    await sse_queue.put({
        "type": "dreaming_run_started",
        "run_id": run.id,
        "days": days,
        "min_actions": min_actions,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })

    try:
        # Light phase: fetch recent actions (paginate to handle >1000 entries)
        all_actions: list[ActionMemory] = []
        page = 1
        while True:
            result = await action_service.list_action_memories(db, page=page, size=100)
            all_actions.extend(result["items"])
            if page >= result["pages"]:
                break
            page += 1
        recent_actions = _filter_recent_actions(all_actions, days)

        run.action_memories_analyzed = len(recent_actions)

        if len(recent_actions) < min_actions:
            run.status = "success"
            run.finished_at = datetime.now(timezone.utc)
            run.summary = f"Only {len(recent_actions)} actions in last {days} days — skipping (minimum: {min_actions})"
            await sse_queue.put({
                "type": "dreaming_run_completed",
                "run_id": run.id,
                "status": run.status,
                "reason": run.summary,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })
            await db.commit()
            return {"status": "skipped", "reason": run.summary, "run_id": run.id}

        # REM phase: extract patterns
        patterns = _extract_patterns(recent_actions)
        run.patterns_found = (
            len(patterns.get("frequent_tags", []))
            + len(patterns.get("recurring_errors", []))
        )

        # Deep phase: create dream note
        note = await _create_dream_note(db, patterns, run)
        run.notes_created = 1 if note else 0

        run.status = "success"
        run.finished_at = datetime.now(timezone.utc)
        run.summary = f"Dream diary created: {note.title if note else 'none'}"
        await sse_queue.put({
            "type": "dreaming_run_completed",
            "run_id": run.id,
            "status": run.status,
            "notes_created": run.notes_created,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })
        await db.commit()

        # Final step: turn recurring failure patterns into draft proposals for review.
        # Never lets gap analysis failures sour an otherwise-successful dreaming run.
        new_proposals: list[dict[str, Any]] = []
        try:
            from app.locutus.gap_analysis import run_gap_analysis

            new_logs = await run_gap_analysis(db, recent_actions, run_id=f"dreaming-{run.id}")
            new_proposals = [
                {"id": log.id, "title": log.title, "trigger_description": log.trigger_description}
                for log in new_logs
            ]
            if new_proposals:
                await sse_queue.put({
                    "type": "gap_analysis_completed",
                    "run_id": run.id,
                    "proposals": new_proposals,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                })
        except Exception:
            logger.exception(f"Gap analysis failed for dreaming run #{run.id}")

        return {
            "status": "success",
            "run_id": run.id,
            "actions_analyzed": run.action_memories_analyzed,
            "patterns_found": run.patterns_found,
            "notes_created": run.notes_created,
            "note_title": note.title if note else None,
            "gap_proposals": new_proposals,
        }

    except Exception as e:
        run.status = "failed"
        run.finished_at = datetime.now(timezone.utc)
        run.error = str(e)
        await sse_queue.put({
            "type": "dreaming_run_completed",
            "run_id": run.id,
            "status": run.status,
            "error": str(e),
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })
        await db.commit()
        raise


async def get_dreaming_runs(
    db: AsyncSession,
    page: int = 1,
    size: int = 20,
) -> dict:
    """Get Dreaming run history."""
    page = max(1, page)
    size = max(1, min(100, size))

    query = select(DreamingRun).order_by(DreamingRun.started_at.desc())

    count_query = select(func.count()).select_from(query.subquery())
    total = (await db.execute(count_query)).scalar() or 0

    offset = (page - 1) * size
    items_result = await db.execute(
        query.offset(offset).limit(size)
    )
    items = list(items_result.scalars().all())

    pages = math.ceil(total / size) if total > 0 else 0

    return {
        "items": items,
        "total": total,
        "page": page,
        "size": size,
        "pages": pages,
    }
